config/routes.rb
Zanhealth::Application.routes.draw do

  resources :item_groups

  resources :departments
  resources :facilities
  devise_for :users, :controllers => {:registrations => "registrations" }
  resources :parts
  resources :roles
  resources :texts
  resources :settings

  get '/qr/:id' => "shortener/shortened_urls#show"

  resources :bmet_items, except: :show do
    collection { post :import }
    collection { post :stage_import }
    collection { get :search }
  end
  resources :bmet_item_histories
  resources :bmet_labor_hours
  resources :bmet_models
  resources :bmet_needs
  resources :bmet_preventative_maintenances, except: :show do
  	  collection { get :search }
  end

  resources :bmet_work_orders, except: :show do
	  collection { get :search }
  end
  resources :bmet_work_order_comments
  resources :bmet_work_requests, except: :show do
  	  collection { get :search }
  end
  resources :bmet_costs
  resources :bmet_cost_items
  resources :part_transactions
  
  resources :facility_work_orders, except: :show do
      collection { get :search }
  end
  resources :facility_work_order_comments
  resources :facility_costs
  resources :facility_labor_hours
  resources :facility_preventative_maintenances, except: :show do
    collection { get :search }
  end
  resources :facility_work_requests, except: :show  do
    collection { get :search }
  end
  resources :facility_cost_items
  

  get "/facility_preventative_maintenances/download", to: "facility_preventative_maintenances#as_csv"
  get "/facility_work_orders/download", to: "facility_work_orders#as_csv"
  get "/facility_work_requests/download", to: "facility_work_requests#as_csv"

  get "/bmet_work_orders/download", to: "bmet_work_orders#as_csv"
  get "/bmet_preventative_maintenances/download", to: "bmet_preventative_maintenances#as_csv"
  get "/bmet_work_requests/download", to: "bmet_work_requests#as_csv"
  get "/bmet_items/download", to: "bmet_items#as_csv"
  get "/bmet_items/:id", to: "bmet_items#show"
  get "/bmet_items_confirm_import", to: "bmet_items#confirm_import"
  get "/import", to: "bmet_items#show_import_page"
  post "/bmet_items_import", to: "bmet_items#import"
  post "/bmet_items_cancel_import", to: "bmet_items#cancel_import"
  get "/bmet_items_main_list_print_view", to: "bmet_items#show_main_list_print"
  get "/bmet_items_main_list_print_view_by_department", to: "bmet_items#show_main_list_print_by_department"

  
  get "/facility_dashboard/status", to: "facility_dashboard#status"
  get "/facility_dashboard/wo_finances", to: "facility_dashboard#wo_finances"
  get "/facility_dashboard/labor_hours", to: "facility_dashboard#labor_hours"
  get "/facility_dashboard/statusAjax", to: "facility_dashboard#statusAjax"
  get "/facility_dashboard/indexAjax", to: "facility_dashboard#indexAjax"
  get "/facility_dashboard/calendarAjax", to: "facility_dashboard#calendarAjax"
  get "/facility_dashboard/timelineAjax", to: "facility_dashboard#timelineAjax"

  get "/facility_dashboard/statusExpireAjaxhtml", to: "facility_dashboard#statusExpireAjaxhtml"
  resources :facility_dashboard

  get "/bmet_dashboard/status", to: "bmet_dashboard#status"
  get "/bmet_dashboard/wo_finances", to: "bmet_dashboard#wo_finances"
  get "/bmet_dashboard/labor_hours", to: "bmet_dashboard#labor_hours"
  get "/bmet_dashboard/status_ajax", to: "bmet_dashboard#statusAjax"
  get "/bmet_dashboard/timelineAjax", to: "bmet_dashboard#timelineAjax"
  get "/bmet_dashboard/status/wo_expire", to: "bmet_dashboard#status"
  get "/bmet_dashboard/status/wo_completed", to: "bmet_dashboard#statusWoCompleted"
  get "/bmet_dashboard/status/wo_expire_ajax", to: "bmet_dashboard#statusAjax"
  get "/bmet_dashboard/status/wo_completed_ajax", to: "bmet_dashboard#statusWoCompletedAjax"
  get "/bmet_dashboard/status/wo_department", to: "bmet_dashboard#statusWoDepartment"
  get "/bmet_dashboard/status/wo_department_ajax", to: "bmet_dashboard#statusWoDepartmentAjax"
  get "/bmet_dashboard/status/wo_owner", to: "bmet_dashboard#statusWoOwner"
  get "/bmet_dashboard/status/wo_owner_ajax", to: "bmet_dashboard#statusWoOwnerAjax"
  get "/bmet_dashboard/wo_finances/department", to: "bmet_dashboard#wo_finances"
  get "/bmet_dashboard/wo_finances/item", to: "bmet_dashboard#wo_finances_item"

  get "/bmet_dashboard/labor_hours/time_worked", to: "bmet_dashboard#labor_hours_time_worked"
  get "/bmet_dashboard/labor_hours/item", to: "bmet_dashboard#labor_hours_item"
  get "/bmet_dashboard/labor_hours/work_order", to: "bmet_dashboard#labor_hours_work_order"

  get "/bmet_dashboard/items/percent_down", to: "bmet_dashboard#items_percent_down"
  get "/bmet_dashboard/items/item_wo_created", to: "bmet_dashboard#items_wo_created"

  get "/bmet_dashboard/timeDropdownAjax", to: "bmet_dashboard#timeDropdownAjax"
  get "/bmet_dashboard/noneDropdownAjax", to: "bmet_dashboard#noneDropdownAjax"
  resources :bmet_dashboard

  put "hide_facility_work_order/:id", to:"facility_work_orders#hide", :as => :hide_facility_work_order
  get "/facility_work_orders/unhidden", to: "facility_work_orders#index"
  get "/facility_work_orders/unhidden/:id", to: "facility_work_orders#show"
  get "/facility_work_orders/hidden/", to: "facility_work_orders#hidden"
  get "/facility_work_orders/hidden/:id", to: "facility_work_orders#show_hidden"
  get "/facility_work_orders/all/", to: "facility_work_orders#all"
  get "/facility_work_orders/all/:id", to: "facility_work_orders#show_all"
  get "/facility_work_orders/:id", to: "facility_work_orders#show_all"

  put "hide_facility_preventative_maintenance/:id", to: "facility_preventative_maintenances#hide", :as => :hide_facility_preventative_maintenance
  get "/facility_preventative_maintenances/unhidden", to: "facility_preventative_maintenances#index"
  get "/facility_preventative_maintenances/unhidden/:id", to: "facility_preventative_maintenances#show"
  get "/facility_preventative_maintenances/hidden", to: "facility_preventative_maintenances#hidden"
  get "/facility_preventative_maintenances/hidden/:id", to: "facility_preventative_maintenances#show_hidden"
  get "/facility_preventative_maintenances/all", to: "facility_preventative_maintenances#all"
  get "/facility_preventative_maintenances/all/:id", to: "facility_preventative_maintenances#show_all"
  put "/reset_facility_preventative_maintenance/:id", to: "facility_preventative_maintenances#reset"

  put "hide_facility_work_request/:id", to: "facility_work_requests#hide", :as => :hide_facility_work_request
  get "/facility_work_requests/unhidden", to: "facility_work_requests#index"
  get "/facility_work_requests/unhidden/:id", to: "facility_work_requests#show"
  get "/facility_work_requests/hidden", to: "facility_work_requests#hidden"
  get "/facility_work_requests/hidden/:id", to: "facility_work_requests#show_hidden"
  get "/facility_work_requests/all", to: "facility_work_requests#all"
  get "/facility_work_requests/all/:id", to: "facility_work_requests#show_all"

  put "hide_bmet_work_order/:id", to: "bmet_work_orders#hide", :as => :hide_bmet_work_order
  get "/bmet_work_orders/unhidden", to: "bmet_work_orders#index"
  get "/bmet_work_orders/unhidden/:id", to: "bmet_work_orders#show"
  get "/bmet_work_orders/hidden", to: "bmet_work_orders#hidden"
  get "/bmet_work_orders/hidden/:id", to: "bmet_work_orders#show_hidden"
  get "/bmet_work_orders/all", to: "bmet_work_orders#all"
  get "/bmet_work_orders/all/:id", to: "bmet_work_orders#show_all"
  get "/bmet_work_orders/print_view/:id", to: "bmet_work_orders#show_print"

  put "hide_bmet_work_request/:id", to: "bmet_work_requests#hide", :as => :hide_bmet_work_request
  get "/bmet_work_requests/unhidden", to: "bmet_work_requests#index"
  get "/bmet_work_requests/unhidden/:id", to: "bmet_work_requests#show"
  get "/bmet_work_requests/hidden", to: "bmet_work_requests#hidden"
  get "/bmet_work_requests/hidden/:id", to: "bmet_work_requests#show_hidden"
  get "/bmet_work_requests/all", to: "bmet_work_requests#all"
  get "/bmet_work_requests/all/:id", to: "bmet_work_requests#show_all"

  put "hide_bmet_preventative_maintenance/:id", to: "bmet_preventative_maintenances#hide", :as => :hide_bmet_preventative_maintenance 
  get "/bmet_preventative_maintenances/unhidden", to: "bmet_preventative_maintenances#index"
  get "/bmet_preventative_maintenances/unhidden/:id", to: "bmet_preventative_maintenances#show"
  get "/bmet_preventative_maintenances/hidden", to: "bmet_preventative_maintenances#hidden"
  get "/bmet_preventative_maintenances/hidden/:id", to: "bmet_preventative_maintenances#show_hidden"
  get "/bmet_preventative_maintenances/all", to: "bmet_preventative_maintenances#all"
  get "/bmet_preventative_maintenances/all/:id", to: "bmet_preventative_maintenances#show_all"
  put "/reset_bmet_preventative_maintenance/:id", to: "bmet_preventative_maintenances#reset"

  get "/facility_work_requests/:facility_id/public_new", to: "facility_work_requests#public_new"  
  post "/facility_work_requests/public_create", to: "facility_work_requests#public_create"  
  get "/facility_work_requests/public_show/:id", to: "facility_work_requests#public_show"  

  get "/bmet_work_requests/:facility_id/public_new", to: "bmet_work_requests#public_new"  
  post "/bmet_work_requests/public_create", to: "bmet_work_requests#public_create"  
  get "/bmet_work_requests/public_show/:id", to: "bmet_work_requests#public_show"  

  get "/my_bmet_work_orders", to: "bmet_work_orders#my"
  get "/detailed_bmet_work_orders", to: "bmet_work_orders#detailed"
  get "/detailed_items", to: "bmet_items#detailed"
  get "/text", to: "text#receive"

  get "/settings", to: "settings#index"
  post "/settings/create_user", to: "settings#create_user"
  post "/settings/create_department", to: "settings#create_department"
  post "/settings/create_item_group", to: "settings#create_item_group"
  post "/settings/update_user", to: "settings#update_user"

    
  get "/admin", to: "admin#index"
  get "/admin/print_tags_form", to: "admin#print_tags_form"

app/controllers/facility_work_requests_controller.rb
class FacilityWorkRequestsController < ApplicationController
  load_and_authorize_resource :except => [:public_new, :public_create, :public_show]
before_action :set_facility_work_request, only: [:show, :update, :destroy, :edit, :show_hidden, :show_all]
before_action :set_facility_work_requests, only:[:new, :index, :show, :search]
before_action :set_status, only: [:show, :hidden, :all, :show_all, :show_hidden]
before_action :set_users, only: [:show, :hidden, :all, :show_all, :show_hidden], except: [:new, :create]
before_action :set_departments, only: [:show, :hidden, :all, :show_all, :show_hidden]
before_action :set_hidden_facility_work_requests, only: [:hidden, :show_hidden]
before_action :set_all_facility_work_requests, only: [:all, :show_all]
before_action :set_convert_object, only: [:show, :show_all, :show_hidden]
skip_before_action :authenticate_user!, only: [:public_new, :public_create, :public_show]

  layout 'layouts/facilities_app'

  def search
    @facility_work_requests = FacilityWorkRequest.search(params[:q], :size => 100).records
    @facility_work_requests = @facility_work_requests.with_deleted.where(:facility_id => current_user.facility_id).all.to_a
    @link = facility_work_requests_url+"/all/"
    render action: "index"
  end

  def new
    @facility_work_request = FacilityWorkRequest.new
  end

  def edit
  end

  def as_csv
    @facility_work_requests = FacilityWorkRequest.with_deleted.where(:facility_id => current_user.facility_id)
    send_data @facility_work_requests.as_csv, type: "text/csv", filename: "facility_work_requests.csv"
  end

  def index  	  
  end

  def hidden
  	  render 'index'
  end

  def all
  	  render 'index'
  end

  def show

  end

  def show_hidden
 	 	render 'show'
  end
 
  def show_all  	
 	  render 'show'
  end

  def update
    respond_to do |format|
      if @facility_work_request.update(facility_work_request_params)
      	link = request.referer.split("/")[-2]
      	if link == "hidden"
      		format.html { redirect_to facility_work_requests_url+"/hidden/"+@facility_work_request.id.to_s, notice: 'Work request was successfully updated. ' }
		    elsif link == "all"
      		format.html { redirect_to facility_work_requests_url+"/all/"+@facility_work_request.id.to_s, notice: 'Work request was successfully updated. ' }
      	else
      		format.html { redirect_to facility_work_requests_url+"/unhidden/"+@facility_work_request.id.to_s, notice: 'Work request was successfully updated. ' }
		    end
        format.json { head :no_content }
      else
        format.html { redirect_to :back }
        format.json { render json: @facility_work_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @facility_work_request = FacilityWorkRequest.new(facility_work_request_params)
    @facility_work_request.facility_id=current_user.facility_id

    respond_to do |format|
      if @facility_work_request.save
        format.html { redirect_to facility_work_requests_url+"/unhidden/"+@facility_work_request.id.to_s, notice: 'Work request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @facility_work_request }
      else
        format.html { redirect_to :back }
        format.json { render json: @facility_work_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def public_new    
    @facility_work_request = FacilityWorkRequest.new
    @facility_work_request.facility_id = params[:facility_id]
    render :layout => "application"
  end

  def public_create    
    @facility_work_request = FacilityWorkRequest.new(facility_work_request_params)

    respond_to do |format|
      # if verify_recaptcha(private_key: ENV['RECAPTCHA_PRIVATE_KEY']) && @facility_work_request.save
      if @facility_work_request.save
        format.html { redirect_to '/facility_work_requests/public_show/'+@facility_work_request.id.to_s, notice: 'Work request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @facility_work_request }
      else
        format.html { render action: 'public_new', layout: "application" }
        format.json { render json: @facility_work_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def public_show
    @facility_work_request = FacilityWorkRequest.find_by_id(params[:id])
    render :layout => "application"
  end

  def destroy
    @facility_work_request.really_destroy!
    respond_to do |format|
      link = request.referer.split("/")[-2]
      if link == "hidden"
        format.html { redirect_to facility_work_requests_url+"/hidden/", notice: 'Work request was successfully deleted.' }
      elsif link == "all"
        format.html { redirect_to facility_work_requests_url+"/all/", notice: 'Work request was successfully deleted.' }
      else
        format.html { redirect_to facility_work_requests_url+"/unhidden/", notice: 'Work request was successfully deleted.' }
      end
      format.json { head :no_content }
    end
  end

  def hide
  	@facility_work_request = FacilityWorkRequest.with_deleted.find_by_id(params[:id])
  	if @facility_work_request.destroyed?
  		FacilityWorkRequest.restore(@facility_work_request.id)
  	else
  		@facility_work_request.destroy
  	end
  	respond_to do |format|
  		link = "/"+request.referer.split("/")[-2]
  		if link == "/all"
  			format.html { redirect_to request.referer }
  		else
  			link = facility_work_requests_url+link
  			format.html { redirect_to link }
  		end
  		format.json { head :no_content }
  	end
  end

  private 
    def set_status
      @status= {
        'Unstarted' => 0,
        'In Progress' => 1,
        'Completed' => 2
      }
    end

    def set_users
      @users = User.where(:facility_id => current_user.facility_id).all.to_a
    end

    def set_departments
      @departments = Department.where(:facility_id => current_user.facility_id).all.to_a
    end

    def set_facility_work_request
      @facility_work_request = FacilityWorkRequest.with_deleted.find_by_id(params[:id])
      if (@facility_work_request==nil || @facility_work_request.facility_id!=current_user.facility_id)
          @facility_work_request=nil
          redirect_to "/404"
      end
    end

    def set_facility_work_requests
      @facility_work_requests = FacilityWorkRequest.where(:facility_id => current_user.facility_id).all.to_a
      @link = facility_work_requests_url+"/unhidden/"
    end

   def set_hidden_facility_work_requests
      @facility_work_requests = FacilityWorkRequest.only_deleted.where(:facility_id => current_user.facility_id).all.to_a
      @link = facility_work_requests_url+"/hidden/"
    end

    def set_all_facility_work_requests
      @facility_work_requests = FacilityWorkRequest.with_deleted.where(:facility_id => current_user.facility_id).order(:created_at).reverse_order().all.to_a
      @link = facility_work_requests_url+"/all/"
    end

    def facility_work_request_params
      params.require(:facility_work_request).permit(:id, :requester, :department, :location, :phone, :email, :description, :created_at, :updated_at, :facility_id)
    end

    def set_convert_object
      @input_object = FacilityWorkOrder.new
      @input_object.description = "Description: "+ @facility_work_request.description + "\n"+
      "Location: "+@facility_work_request.location + "\n" +
      "Email: "+@facility_work_request.email + "\n" +
      "Phone: "+@facility_work_request.phone + "\n"
      @input_object.pm_origin = nil
      @input_object.wr_origin = @facility_work_request

    end
    
end

app/helpers/facility_work_requests_helper.rb
module FacilityWorkRequestsHelper
end

app/views/facility_work_requests/_form.html.erb
<%= form_for(@facility_work_request) do |f| %>
  <% if @facility_work_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility_work_request.errors.count, "error") %> prohibited this facility_work_request from being saved:</h2>
<ul> <% @work_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <!-- can put inside the url parameter but shouldn't be able to imposter as another user -->
    <% if params[:action] == 'new' %>
        <div class="work_request_form-field">
        <input type="hidden" name="facility_work_request[requester_id]" value=<%= session[:user] %>> </input>
        </div>
    <% elsif params[:action] == 'edit' %>
    <% end %>
    <div id="object-form-single-col">

      <div class="field-box">
        <div class="field-type"><%= t(:requester).capitalize %></div>
        <div class="field-info"><%= f.text_area :requester, :required => true %></div>
      </div>
      <div class="field-box">
        <div class="field-type"><%= t(:department).capitalize %></div>
        <div class="field-info"><%= f.text_area :department, :required => true %></div>
      </div>
      <div class="field-box">
        <div class="field-type"><%= t(:location).capitalize %><br></div>
        <div class="field-info"><%= f.text_area :location, :required => true%></div>
      </div>
      <div class="field-box">
        <div class="field-type"><%= t(:telephone_number).titlecase %><br></div>
        <div class="field-info"><%= f.telephone_field :phone, :required => true %></div>
      </div>

      <div class="field-box">
        <div class="field-type"><%= t(:email).capitalize %><br></div>
        <div class="field-info"><%= f.email_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'%></div>
      </div>

      <div class="field-box">
        <div class="field-type"><%= t(:description).capitalize %><br></div>
        <div class="field-info"><%= f.text_area :description, :required => true%></div>
      </div>

      <div class="action_submit">
        <%= f.submit t(:create_facility_work_request).titlecase %>
      </div>
    </div>
<% end %>

app/views/facility_work_requests/_form2.html.erb
<% @facility_work_request = FacilityWorkRequest.new %>
<%= form_for(@facility_work_request) do |f| %>
  <% if @facility_work_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility_work_request.errors.count, "error") %> prohibited this facility_work_request from being saved:</h2>
<ul> <% @work_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- can put inside the url parameter but shouldn't be able to imposter as another user -->
  <% if params[:action] == 'new' %>
      <div class="work_request_form-field">
      <input type="hidden" name="facility_work_request[requester_id]" value=<%= session[:user] %>> </input>
      </div>
  <% elsif params[:action] == 'edit' %>
  <% end %>

  <div class = "work_request_form-short">
    <%= @language['Requester'] %><br>
    <%= f.text_area :requester, :required => true %>
  </div>

  <div class = "work_request_form-short">
  	<%= @language['Department'] %><br>
  	<%= f.text_area :department, :required => true %>
  </div>

  <div class="work_request_form-long">
    <%= @language['Location'] %><br>
    <%= f.text_area :location, :required => true %>
  </div>

  <div class = "work_request_form-short">
  	<%= @language['Telephone number'] %><br>
  	<%= f.number_field :department, :required => true %>
  </div>

  <div class = "work_request_form-short">
  	<%= @language['Email'] %><br>
  	<%= f.text_area :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
  </div>

  <div class = "work_request_form-long">
    <%= @language['Description'] %><br>
    <%= f.text_area :description, :required => true %>
  </div>

  <div class="actions">
    <%= f.submit @language['Create Facility Work Request'] %>
  </div>
<% end %>

app/views/facility_work_requests/_interaction_bar.html.erb
<div id='left-top'>
  <div id="top-dropdown">
    &nbsp&nbsp&nbsp&nbsp
    <%= t(:sort).capitalize %>: <div class="dropdown">
      <a id="facworkorder_sort" role="button" data-toggle="dropdown" href="#">
        <%= t(:select_attribute).titlecase %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu dropdown-menu-form" role="menu" aria-labelledby="facworkorder_sort">
       <div>
       <a onclick = "sort_by_name('requester')">
        <%=t(:requester).capitalize%>
       </a>
       </div>
       <div>
       <a onclick = "sort_by_num('Department')">
        <%=t(:department).capitalize%>
       </a>
       </div>
      </ul>
    </div>
    &nbsp&nbsp&nbsp&nbsp
	<%= "View" %>
	<div class="dropdown">
		<a id="facworkorder_sort" role="button" data-toggle="dropdown" href="#">
			Select View
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu dropdown-menu-form" role="menu" aria-labelledby="facworkorder_sort">
			<div>
				<a href="<%= facility_work_requests_url+"/unhidden" %>">
					Visible Work Requests
				</a>
			</div>
			<div>
				<a href="<%= facility_work_requests_url+"/hidden" %>">
					Hidden Work Requests
				</a>
			</div>
			<div>
				<a href="<%= facility_work_requests_url+"/all" %>">
					All Work Requests
				</a>
			</div>
		</ul>

	</div>
    &nbsp&nbsp&nbsp&nbsp
    <%= form_tag search_facility_work_requests_path, method: 'get' do %>
      <%= text_field_tag :q, params[:q] %>
      <%= submit_tag :search %>
    <% end %>
  </div>
  <div id="top-button">
    <%= link_to "", '#', onclick: "printmainpage(); return false;", :id => "print-button" %>
    <a href= "<%=new_facility_work_request_path%>" id='add-button'></a>
	<%= link_to t(:export_data).titlecase, facility_work_requests_url+"/download" %>
  </div>
</div>

app/views/facility_work_requests/_object_new.html.erb
<div id="object-single-col-box">
	<%= render :partial =>'form'%>
</div>

app/views/facility_work_requests/_object_summary.html.erb
<div id="object-single-col-box">
  <ul class="tab-navigation-buttons">
    <li class="active"><a href="#view" data-toggle="tab">
    	<%= t(:view).capitalize %>
    </a></li>
    <li><a href="#convert" data-toggle="tab"><%= t(:convert_to_work_order).titlecase %></a></li>  
    <% if can? :hide, current_user %>
      <li>
      <% if @facility_work_request.destroyed? %>
    	  <%= link_to t(:unhide).capitalize, hide_facility_work_request_path(@facility_work_request), title: "Unhide work request", rel: "tooltip", method: :put, :required => true %>
      <% else %>
    	  <%= link_to t(:hide).capitalize, hide_facility_work_request_path(@facility_work_request), title: "Hide work request", rel: "tooltip", method: :put, :required => true %>
     <% end %>
    </li>
    <% end %>
    <li><%= link_to t(:delete_forever).titlecase, @facility_work_request, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="view">
    	<%= render :partial => 'object_view' %>
    </div>
    <div class="tab-pane" id="convert">
    	<%= render :partial => 'facility_work_orders/object_convert' %>  	
    </div>  
  </div>
</div>

app/views/facility_work_requests/_public_form.html.erb
<%= simple_form_for @facility_work_request, { url:  facility_work_requests_public_create_path } do |f| %>
  <% if @facility_work_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility_work_request.errors.count, "error") %> prohibited this facility_work_request from being saved:</h2>
<ul> <% @work_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" name="facility_work_request[facility_id]" value=<%= @facility_work_request.facility_id %>> </input>  
  
  <div class = "work_request_form-short">
    <%= t(:requester).capitalize %><br>
    <%= f.text_area :requester, :required => true %>
  </div>

  <div class = "work_request_form-short">
  	<%= t(:department).capitalize %><br>
  	<%= f.text_area :department, :required => true %>
  </div>

  <div class="work_request_form-long">
    <%= t(:location).capitalize %><br>
    <%= f.text_area :location, :required => true %>
  </div>

  <div class = "work_request_form-short">
  	<%= t(:telephone_number).titlecase %><br>
  	<%= f.number_field :phone, :required => true %>
  </div>

  <div class = "work_request_form-short">
  	<%= t(:email).capitalize %><br>
  	<%= f.text_area :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
  </div>

  <div class = "work_request_form-long">
    <%= t(:description).capitalize %><br>
    <%= f.text_area :description, :required => true %>
  </div>

  <div class="actions">
    <%= recaptcha_tags %>
    <%= f.submit t(:create_facility_work_request).titlecase %>
  </div>
<% end %>

app/views/facility_work_requests/edit.html.erb
<h1>Editing facility_work_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility_work_request %> |
<%= link_to 'Back', facility_work_requests_path %>

app/views/facility_work_requests/index.html.erb
<%= render :partial => 'interaction_bar', :layout => 'layouts/topbar' %>

<%= render :partial => 'main_list', :layout => 'layouts/col2' %>

<div class="vertical-divider"></div>

<%= render :partial =>'blank_box', :layout =>'layouts/col3' %>

app/views/facility_work_requests/new.html.erb
<%= render :partial => 'interaction_bar', :layout => 'layouts/topbar' %>

<%= render :partial => 'main_list', :layout => 'layouts/col2' %>

<div class="vertical-divider"></div>

<%= render :partial =>'object_new', :layout =>'layouts/col3' %>

app/views/facility_work_requests/public_new.html.erb
<h1><%=t(:new_work_request).titlecase%></h1>
<%= render :partial => 'public_form' %>