config/routes.rb
Zanhealth::Application.routes.draw do

  resources :item_groups

  resources :departments
  resources :facilities
  devise_for :users, :controllers => {:registrations => "registrations" }
  resources :parts
  resources :roles
  resources :texts
  resources :settings

  get '/qr/:id' => "shortener/shortened_urls#show"

  resources :bmet_items, except: :show do
    collection { post :import }
    collection { post :stage_import }
    collection { get :search }
  end
  resources :bmet_item_histories
  resources :bmet_labor_hours
  resources :bmet_models
  resources :bmet_needs
  resources :bmet_preventative_maintenances, except: :show do
  	  collection { get :search }
  end

  resources :bmet_work_orders, except: :show do
	  collection { get :search }
  end
  resources :bmet_work_order_comments
  resources :bmet_work_requests, except: :show do
  	  collection { get :search }
  end
  resources :bmet_costs
  resources :bmet_cost_items
  resources :part_transactions
  
  resources :facility_work_orders, except: :show do
      collection { get :search }
  end
  resources :facility_work_order_comments
  resources :facility_costs
  resources :facility_labor_hours
  resources :facility_preventative_maintenances, except: :show do
    collection { get :search }
  end
  resources :facility_work_requests, except: :show  do
    collection { get :search }
  end
  resources :facility_cost_items
  

  get "/facility_preventative_maintenances/download", to: "facility_preventative_maintenances#as_csv"
  get "/facility_work_orders/download", to: "facility_work_orders#as_csv"
  get "/facility_work_requests/download", to: "facility_work_requests#as_csv"

  get "/bmet_work_orders/download", to: "bmet_work_orders#as_csv"
  get "/bmet_preventative_maintenances/download", to: "bmet_preventative_maintenances#as_csv"
  get "/bmet_work_requests/download", to: "bmet_work_requests#as_csv"
  get "/bmet_items/download", to: "bmet_items#as_csv"
  get "/bmet_items/:id", to: "bmet_items#show"
  get "/bmet_items_confirm_import", to: "bmet_items#confirm_import"
  get "/import", to: "bmet_items#show_import_page"
  post "/bmet_items_import", to: "bmet_items#import"
  post "/bmet_items_cancel_import", to: "bmet_items#cancel_import"
  get "/bmet_items_main_list_print_view", to: "bmet_items#show_main_list_print"
  get "/bmet_items_main_list_print_view_by_department", to: "bmet_items#show_main_list_print_by_department"

  
  get "/facility_dashboard/status", to: "facility_dashboard#status"
  get "/facility_dashboard/wo_finances", to: "facility_dashboard#wo_finances"
  get "/facility_dashboard/labor_hours", to: "facility_dashboard#labor_hours"
  get "/facility_dashboard/statusAjax", to: "facility_dashboard#statusAjax"
  get "/facility_dashboard/indexAjax", to: "facility_dashboard#indexAjax"
  get "/facility_dashboard/calendarAjax", to: "facility_dashboard#calendarAjax"
  get "/facility_dashboard/timelineAjax", to: "facility_dashboard#timelineAjax"

  get "/facility_dashboard/statusExpireAjaxhtml", to: "facility_dashboard#statusExpireAjaxhtml"
  resources :facility_dashboard

  get "/bmet_dashboard/status", to: "bmet_dashboard#status"
  get "/bmet_dashboard/wo_finances", to: "bmet_dashboard#wo_finances"
  get "/bmet_dashboard/labor_hours", to: "bmet_dashboard#labor_hours"
  get "/bmet_dashboard/status_ajax", to: "bmet_dashboard#statusAjax"
  get "/bmet_dashboard/timelineAjax", to: "bmet_dashboard#timelineAjax"
  get "/bmet_dashboard/status/wo_expire", to: "bmet_dashboard#status"
  get "/bmet_dashboard/status/wo_completed", to: "bmet_dashboard#statusWoCompleted"
  get "/bmet_dashboard/status/wo_expire_ajax", to: "bmet_dashboard#statusAjax"
  get "/bmet_dashboard/status/wo_completed_ajax", to: "bmet_dashboard#statusWoCompletedAjax"
  get "/bmet_dashboard/status/wo_department", to: "bmet_dashboard#statusWoDepartment"
  get "/bmet_dashboard/status/wo_department_ajax", to: "bmet_dashboard#statusWoDepartmentAjax"
  get "/bmet_dashboard/status/wo_owner", to: "bmet_dashboard#statusWoOwner"
  get "/bmet_dashboard/status/wo_owner_ajax", to: "bmet_dashboard#statusWoOwnerAjax"
  get "/bmet_dashboard/wo_finances/department", to: "bmet_dashboard#wo_finances"
  get "/bmet_dashboard/wo_finances/item", to: "bmet_dashboard#wo_finances_item"

  get "/bmet_dashboard/labor_hours/time_worked", to: "bmet_dashboard#labor_hours_time_worked"
  get "/bmet_dashboard/labor_hours/item", to: "bmet_dashboard#labor_hours_item"
  get "/bmet_dashboard/labor_hours/work_order", to: "bmet_dashboard#labor_hours_work_order"

  get "/bmet_dashboard/items/percent_down", to: "bmet_dashboard#items_percent_down"
  get "/bmet_dashboard/items/item_wo_created", to: "bmet_dashboard#items_wo_created"

  get "/bmet_dashboard/timeDropdownAjax", to: "bmet_dashboard#timeDropdownAjax"
  get "/bmet_dashboard/noneDropdownAjax", to: "bmet_dashboard#noneDropdownAjax"
  resources :bmet_dashboard

  put "hide_facility_work_order/:id", to:"facility_work_orders#hide", :as => :hide_facility_work_order
  get "/facility_work_orders/unhidden", to: "facility_work_orders#index"
  get "/facility_work_orders/unhidden/:id", to: "facility_work_orders#show"
  get "/facility_work_orders/hidden/", to: "facility_work_orders#hidden"
  get "/facility_work_orders/hidden/:id", to: "facility_work_orders#show_hidden"
  get "/facility_work_orders/all/", to: "facility_work_orders#all"
  get "/facility_work_orders/all/:id", to: "facility_work_orders#show_all"
  get "/facility_work_orders/:id", to: "facility_work_orders#show_all"

  put "hide_facility_preventative_maintenance/:id", to: "facility_preventative_maintenances#hide", :as => :hide_facility_preventative_maintenance
  get "/facility_preventative_maintenances/unhidden", to: "facility_preventative_maintenances#index"
  get "/facility_preventative_maintenances/unhidden/:id", to: "facility_preventative_maintenances#show"
  get "/facility_preventative_maintenances/hidden", to: "facility_preventative_maintenances#hidden"
  get "/facility_preventative_maintenances/hidden/:id", to: "facility_preventative_maintenances#show_hidden"
  get "/facility_preventative_maintenances/all", to: "facility_preventative_maintenances#all"
  get "/facility_preventative_maintenances/all/:id", to: "facility_preventative_maintenances#show_all"
  put "/reset_facility_preventative_maintenance/:id", to: "facility_preventative_maintenances#reset"

  put "hide_facility_work_request/:id", to: "facility_work_requests#hide", :as => :hide_facility_work_request
  get "/facility_work_requests/unhidden", to: "facility_work_requests#index"
  get "/facility_work_requests/unhidden/:id", to: "facility_work_requests#show"
  get "/facility_work_requests/hidden", to: "facility_work_requests#hidden"
  get "/facility_work_requests/hidden/:id", to: "facility_work_requests#show_hidden"
  get "/facility_work_requests/all", to: "facility_work_requests#all"
  get "/facility_work_requests/all/:id", to: "facility_work_requests#show_all"

  put "hide_bmet_work_order/:id", to: "bmet_work_orders#hide", :as => :hide_bmet_work_order
  get "/bmet_work_orders/unhidden", to: "bmet_work_orders#index"
  get "/bmet_work_orders/unhidden/:id", to: "bmet_work_orders#show"
  get "/bmet_work_orders/hidden", to: "bmet_work_orders#hidden"
  get "/bmet_work_orders/hidden/:id", to: "bmet_work_orders#show_hidden"
  get "/bmet_work_orders/all", to: "bmet_work_orders#all"
  get "/bmet_work_orders/all/:id", to: "bmet_work_orders#show_all"
  get "/bmet_work_orders/print_view/:id", to: "bmet_work_orders#show_print"

  put "hide_bmet_work_request/:id", to: "bmet_work_requests#hide", :as => :hide_bmet_work_request
  get "/bmet_work_requests/unhidden", to: "bmet_work_requests#index"
  get "/bmet_work_requests/unhidden/:id", to: "bmet_work_requests#show"
  get "/bmet_work_requests/hidden", to: "bmet_work_requests#hidden"
  get "/bmet_work_requests/hidden/:id", to: "bmet_work_requests#show_hidden"
  get "/bmet_work_requests/all", to: "bmet_work_requests#all"
  get "/bmet_work_requests/all/:id", to: "bmet_work_requests#show_all"

  put "hide_bmet_preventative_maintenance/:id", to: "bmet_preventative_maintenances#hide", :as => :hide_bmet_preventative_maintenance 
  get "/bmet_preventative_maintenances/unhidden", to: "bmet_preventative_maintenances#index"
  get "/bmet_preventative_maintenances/unhidden/:id", to: "bmet_preventative_maintenances#show"
  get "/bmet_preventative_maintenances/hidden", to: "bmet_preventative_maintenances#hidden"
  get "/bmet_preventative_maintenances/hidden/:id", to: "bmet_preventative_maintenances#show_hidden"
  get "/bmet_preventative_maintenances/all", to: "bmet_preventative_maintenances#all"
  get "/bmet_preventative_maintenances/all/:id", to: "bmet_preventative_maintenances#show_all"
  put "/reset_bmet_preventative_maintenance/:id", to: "bmet_preventative_maintenances#reset"

  get "/facility_work_requests/:facility_id/public_new", to: "facility_work_requests#public_new"  
  post "/facility_work_requests/public_create", to: "facility_work_requests#public_create"  
  get "/facility_work_requests/public_show/:id", to: "facility_work_requests#public_show"  

  get "/bmet_work_requests/:facility_id/public_new", to: "bmet_work_requests#public_new"  
  post "/bmet_work_requests/public_create", to: "bmet_work_requests#public_create"  
  get "/bmet_work_requests/public_show/:id", to: "bmet_work_requests#public_show"  

  get "/my_bmet_work_orders", to: "bmet_work_orders#my"
  get "/detailed_bmet_work_orders", to: "bmet_work_orders#detailed"
  get "/detailed_items", to: "bmet_items#detailed"
  get "/text", to: "text#receive"

  get "/settings", to: "settings#index"
  post "/settings/create_user", to: "settings#create_user"
  post "/settings/create_department", to: "settings#create_department"
  post "/settings/create_item_group", to: "settings#create_item_group"
  post "/settings/update_user", to: "settings#update_user"

    
  get "/admin", to: "admin#index"
  get "/admin/print_tags_form", to: "admin#print_tags_form"

app/models/facility_labor_hour.rb
# == Schema Information
#
# Table name: facility_labor_hours
#
#  id                     :integer          not null, primary key
#  date_started           :datetime
#  duration               :integer
#  technician_id          :integer
#  facility_work_order_id :integer
#  created_at             :datetime
#  updated_at             :datetime
#

class FacilityLaborHour < ActiveRecord::Base
  belongs_to :facility_work_order
  belongs_to :technician, :class_name => "User"  
end

app/controllers/facility_labor_hours_controller.rb
class FacilityLaborHoursController < ApplicationController
  load_and_authorize_resource param_method: :labor_hour_params
  before_action :set_labor_hour, only: [:show, :edit, :update, :destroy]

  def index
    @facility_labor_hours=FacilityLaborHour.all
  end
  def new
    @facility_labor_hour = FacilityLaborHour.new
    #@users = User.where(:facility_id => user.facility.id).all.to_a
  end
  # POST /bmet_work_orders
  # POST /bmet_work_orders.json
  def create
    @facility_labor_hour = FacilityLaborHour.new(labor_hour_params)

    respond_to do |format|
      if @facility_labor_hour.save
        format.html { redirect_to :back, notice: 'Work order was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @facility_labor_hour }
      else
        format.html { render action: 'new' }
        format.json { render json: @facility_labor_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @facility_labor_hour.update(labor_hour_params)
        format.html { redirect_to @facility_labor_hour.facility_work_order, notice: 'Facility Labor Hour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @facility_labor_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @facility_labor_hour.destroy
    respond_to do |format|
      link = request.referer.split("/")[-2]
      @facility_work_order = @facility_labor_hour.facility_work_order
      if link == "hidden"
          format.html { redirect_to facility_work_orders_url+"/hidden/"+@facility_work_order.id.to_s, notice: 'Work order was successfully updated.' }
      elsif link == "all"
          format.html { redirect_to facility_work_orders_url+"/all/"+@facility_work_order.id.to_s, notice: 'Work order was successfully updated.' }
      else
          format.html { redirect_to facility_work_orders_url+"/unhidden/"+@facility_work_order.id.to_s, notice: 'Work order was successfully updated.' }
      end
      # format.html { redirect_to @facility_labor_hour.facility_work_order }
      format.json { head :no_content }
    end
  end

  def show      
      @facility_labor_hours=FacilityLaborHour.all
      #@facility_labor_hour=LaborHour.where(:id => params[:id])
  end

  private 
    def set_labor_hour
      @facility_labor_hour = FacilityLaborHour.find_by_id(params[:id])
    end
    def labor_hour_params
      params.require(:facility_labor_hour).permit(:date_started, :duration, :technician_id, :facility_work_order_id, :created_at, :updated_at)
    end
    
end

app/helpers/facility_labor_hours_helper.rb
module FacilityLaborHoursHelper
end

app/views/facility_labor_hours/_facility_labor_hour.html.erb
<li class="facility_labor_hour">  	  

  	<div class="labor_hour-technician">
  		<%= facility_labor_hour.technician.name %>
  	</div>
  	<div class="labor_hour-detail">
  		<span class="labor_hour-date"><%= facility_labor_hour.date_started.try(:strftime,"%^b %d, %Y") %></span>
  		<span class="labor_hour-duration"><%= facility_labor_hour.duration %></span>
  	</div>
	<%= link_to 'X', facility_labor_hour, method: :delete, data: { confirm: 'Are you sure?' } %>
</li>

app/views/facility_labor_hours/_facility_labor_hour_form.html.erb
<div class='extra-details_form-div'>
  <hr class="extra-details_hr">

  <%= form_for(@facility_labor_hour) do |f| %>
    <% if @facility_labor_hour.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@facility_labor_hour.errors.count, "error") %> prohibited this facility_labor_hour from being saved:</h2>
        <ul><% @facility_labor_hour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div id="labor_technician-title">
      <%= t(:technician).capitalize %>
    </div>
    <div id="labor_date-title">
      <%= t(:worked_on).titlecase %>
    </div >
    <div id="labor_hour-title">
      <%= t(:duration).capitalize %>
    </div>
    
    <div id="extra-details_labor_tech">
      <%= f.collection_select :technician_id, @users, :id, :name, :id => "technician" %>        
    </div>
    <div id="extra-details_labor_date">      
      <%= f.date_select :date_started, :required => true,use_short_month: true %>    
    </div>
    <div id="extra-details_labor_hours">    
      <%= f.number_field :duration, :required => true,:placeholder => t(:hr).capitalize %>
    </div>

    <div class="extra-details_actions">
      <%= f.submit :value => ">"%>
    </div>

      
      
      
     
      <div class="field">
        <%= f.hidden_field :facility_work_order_id, value: @facility_work_order.id %>
      </div>

      
  <% end %>
</div>

app/views/facility_labor_hours/_form.html.erb
<%= simple_form_for(@facility_labor_hour) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date_started %>
    <%= f.input :duration %>
    <%= f.input :technician_id %>
    <%= f.input :facility_work_order_id %>
    <%= f.input :created_at %>
    <%= f.input :updated_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/facility_labor_hours/_labor_summary.html.erb
<div>
  <ul>
    <% @facility_labor_hours.each do |facility_labor_hour| %>
      <li>
        <div class="labor-technician">
          Technician ID: <%= facility_labor_hour.technician_id %>
        </div>
        <div class="labor-duration">
          Duration: <%= facility_labor_hour.duration %> hours
        </div>
        <div class="labor-timestamp">
          Time Started: <%= facility_labor_hour.date_started %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/facility_labor_hours/edit.html.erb
<h1>Editing facility_labor_hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility_labor_hour %> |
<%= link_to 'Back', facility_labor_hours_path %>

app/views/facility_labor_hours/index.html.erb
<h1>Listing facility_labor_hours</h1>

<table>
  <thead>
    <tr>
      <th>Date started</th>
      <th>Duration</th>
      <th>Technician</th>
      <th>Facility work order</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @facility_labor_hours.each do |facility_labor_hour| %>
      <tr>
        <td><%= facility_labor_hour.date_started %></td>
        <td><%= facility_labor_hour.duration %></td>
        <td><%= facility_labor_hour.technician_id %></td>
        <td><%= facility_labor_hour.facility_work_order_id %></td>
        <td><%= facility_labor_hour.created_at %></td>
        <td><%= facility_labor_hour.updated_at %></td>
        <td><%= link_to 'Show', facility_labor_hour %></td>
        <td><%= link_to 'Edit', edit_facility_labor_hour_path(facility_labor_hour) %></td>
        <td><%= link_to 'Destroy', facility_labor_hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility labor hour', new_facility_labor_hour_path %>

app/views/facility_labor_hours/new.html.erb
<h1>FacilityLaborHours#new</h1>
<p>Find me in app/views/facility_labor_hours/new.html.erb</p>

app/views/facility_labor_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date started:</strong>
  <%= @facility_labor_hour.date_started %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @facility_labor_hour.duration %>
</p>

<p>
  <strong>Technician:</strong>
  <%= @facility_labor_hour.technician_id %>
</p>

<p>
  <strong>Facility work order:</strong>
  <%= @facility_labor_hour.facility_work_order_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @facility_labor_hour.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @facility_labor_hour.updated_at %>
</p>

<%= link_to 'Edit', edit_facility_labor_hour_path(@facility_labor_hour) %> |
<%= link_to 'Back', facility_labor_hours_path %>