config/routes.rb
Zanhealth::Application.routes.draw do

  resources :item_groups

  resources :departments
  resources :facilities
  devise_for :users, :controllers => {:registrations => "registrations" }
  resources :parts
  resources :roles
  resources :texts
  resources :settings

  get '/qr/:id' => "shortener/shortened_urls#show"

  resources :bmet_items, except: :show do
    collection { post :import }
    collection { post :stage_import }
    collection { get :search }
  end
  resources :bmet_item_histories
  resources :bmet_labor_hours
  resources :bmet_models
  resources :bmet_needs
  resources :bmet_preventative_maintenances, except: :show do
  	  collection { get :search }
  end

  resources :bmet_work_orders, except: :show do
	  collection { get :search }
  end
  resources :bmet_work_order_comments
  resources :bmet_work_requests, except: :show do
  	  collection { get :search }
  end
  resources :bmet_costs
  resources :bmet_cost_items
  resources :part_transactions
  
  resources :facility_work_orders, except: :show do
      collection { get :search }
  end
  resources :facility_work_order_comments
  resources :facility_costs
  resources :facility_labor_hours
  resources :facility_preventative_maintenances, except: :show do
    collection { get :search }
  end
  resources :facility_work_requests, except: :show  do
    collection { get :search }
  end
  resources :facility_cost_items
  

  get "/facility_preventative_maintenances/download", to: "facility_preventative_maintenances#as_csv"
  get "/facility_work_orders/download", to: "facility_work_orders#as_csv"
  get "/facility_work_requests/download", to: "facility_work_requests#as_csv"

  get "/bmet_work_orders/download", to: "bmet_work_orders#as_csv"
  get "/bmet_preventative_maintenances/download", to: "bmet_preventative_maintenances#as_csv"
  get "/bmet_work_requests/download", to: "bmet_work_requests#as_csv"
  get "/bmet_items/download", to: "bmet_items#as_csv"
  get "/bmet_items/:id", to: "bmet_items#show"
  get "/bmet_items_confirm_import", to: "bmet_items#confirm_import"
  get "/import", to: "bmet_items#show_import_page"
  post "/bmet_items_import", to: "bmet_items#import"
  post "/bmet_items_cancel_import", to: "bmet_items#cancel_import"
  get "/bmet_items_main_list_print_view", to: "bmet_items#show_main_list_print"
  get "/bmet_items_main_list_print_view_by_department", to: "bmet_items#show_main_list_print_by_department"

  
  get "/facility_dashboard/status", to: "facility_dashboard#status"
  get "/facility_dashboard/wo_finances", to: "facility_dashboard#wo_finances"
  get "/facility_dashboard/labor_hours", to: "facility_dashboard#labor_hours"
  get "/facility_dashboard/statusAjax", to: "facility_dashboard#statusAjax"
  get "/facility_dashboard/indexAjax", to: "facility_dashboard#indexAjax"
  get "/facility_dashboard/calendarAjax", to: "facility_dashboard#calendarAjax"
  get "/facility_dashboard/timelineAjax", to: "facility_dashboard#timelineAjax"

  get "/facility_dashboard/statusExpireAjaxhtml", to: "facility_dashboard#statusExpireAjaxhtml"
  resources :facility_dashboard

  get "/bmet_dashboard/status", to: "bmet_dashboard#status"
  get "/bmet_dashboard/wo_finances", to: "bmet_dashboard#wo_finances"
  get "/bmet_dashboard/labor_hours", to: "bmet_dashboard#labor_hours"
  get "/bmet_dashboard/status_ajax", to: "bmet_dashboard#statusAjax"
  get "/bmet_dashboard/timelineAjax", to: "bmet_dashboard#timelineAjax"
  get "/bmet_dashboard/status/wo_expire", to: "bmet_dashboard#status"
  get "/bmet_dashboard/status/wo_completed", to: "bmet_dashboard#statusWoCompleted"
  get "/bmet_dashboard/status/wo_expire_ajax", to: "bmet_dashboard#statusAjax"
  get "/bmet_dashboard/status/wo_completed_ajax", to: "bmet_dashboard#statusWoCompletedAjax"
  get "/bmet_dashboard/status/wo_department", to: "bmet_dashboard#statusWoDepartment"
  get "/bmet_dashboard/status/wo_department_ajax", to: "bmet_dashboard#statusWoDepartmentAjax"
  get "/bmet_dashboard/status/wo_owner", to: "bmet_dashboard#statusWoOwner"
  get "/bmet_dashboard/status/wo_owner_ajax", to: "bmet_dashboard#statusWoOwnerAjax"
  get "/bmet_dashboard/wo_finances/department", to: "bmet_dashboard#wo_finances"
  get "/bmet_dashboard/wo_finances/item", to: "bmet_dashboard#wo_finances_item"

  get "/bmet_dashboard/labor_hours/time_worked", to: "bmet_dashboard#labor_hours_time_worked"
  get "/bmet_dashboard/labor_hours/item", to: "bmet_dashboard#labor_hours_item"
  get "/bmet_dashboard/labor_hours/work_order", to: "bmet_dashboard#labor_hours_work_order"

  get "/bmet_dashboard/items/percent_down", to: "bmet_dashboard#items_percent_down"
  get "/bmet_dashboard/items/item_wo_created", to: "bmet_dashboard#items_wo_created"

  get "/bmet_dashboard/timeDropdownAjax", to: "bmet_dashboard#timeDropdownAjax"
  get "/bmet_dashboard/noneDropdownAjax", to: "bmet_dashboard#noneDropdownAjax"
  resources :bmet_dashboard

  put "hide_facility_work_order/:id", to:"facility_work_orders#hide", :as => :hide_facility_work_order
  get "/facility_work_orders/unhidden", to: "facility_work_orders#index"
  get "/facility_work_orders/unhidden/:id", to: "facility_work_orders#show"
  get "/facility_work_orders/hidden/", to: "facility_work_orders#hidden"
  get "/facility_work_orders/hidden/:id", to: "facility_work_orders#show_hidden"
  get "/facility_work_orders/all/", to: "facility_work_orders#all"
  get "/facility_work_orders/all/:id", to: "facility_work_orders#show_all"
  get "/facility_work_orders/:id", to: "facility_work_orders#show_all"

  put "hide_facility_preventative_maintenance/:id", to: "facility_preventative_maintenances#hide", :as => :hide_facility_preventative_maintenance
  get "/facility_preventative_maintenances/unhidden", to: "facility_preventative_maintenances#index"
  get "/facility_preventative_maintenances/unhidden/:id", to: "facility_preventative_maintenances#show"
  get "/facility_preventative_maintenances/hidden", to: "facility_preventative_maintenances#hidden"
  get "/facility_preventative_maintenances/hidden/:id", to: "facility_preventative_maintenances#show_hidden"
  get "/facility_preventative_maintenances/all", to: "facility_preventative_maintenances#all"
  get "/facility_preventative_maintenances/all/:id", to: "facility_preventative_maintenances#show_all"
  put "/reset_facility_preventative_maintenance/:id", to: "facility_preventative_maintenances#reset"

  put "hide_facility_work_request/:id", to: "facility_work_requests#hide", :as => :hide_facility_work_request
  get "/facility_work_requests/unhidden", to: "facility_work_requests#index"
  get "/facility_work_requests/unhidden/:id", to: "facility_work_requests#show"
  get "/facility_work_requests/hidden", to: "facility_work_requests#hidden"
  get "/facility_work_requests/hidden/:id", to: "facility_work_requests#show_hidden"
  get "/facility_work_requests/all", to: "facility_work_requests#all"
  get "/facility_work_requests/all/:id", to: "facility_work_requests#show_all"

  put "hide_bmet_work_order/:id", to: "bmet_work_orders#hide", :as => :hide_bmet_work_order
  get "/bmet_work_orders/unhidden", to: "bmet_work_orders#index"
  get "/bmet_work_orders/unhidden/:id", to: "bmet_work_orders#show"
  get "/bmet_work_orders/hidden", to: "bmet_work_orders#hidden"
  get "/bmet_work_orders/hidden/:id", to: "bmet_work_orders#show_hidden"
  get "/bmet_work_orders/all", to: "bmet_work_orders#all"
  get "/bmet_work_orders/all/:id", to: "bmet_work_orders#show_all"
  get "/bmet_work_orders/print_view/:id", to: "bmet_work_orders#show_print"

  put "hide_bmet_work_request/:id", to: "bmet_work_requests#hide", :as => :hide_bmet_work_request
  get "/bmet_work_requests/unhidden", to: "bmet_work_requests#index"
  get "/bmet_work_requests/unhidden/:id", to: "bmet_work_requests#show"
  get "/bmet_work_requests/hidden", to: "bmet_work_requests#hidden"
  get "/bmet_work_requests/hidden/:id", to: "bmet_work_requests#show_hidden"
  get "/bmet_work_requests/all", to: "bmet_work_requests#all"
  get "/bmet_work_requests/all/:id", to: "bmet_work_requests#show_all"

  put "hide_bmet_preventative_maintenance/:id", to: "bmet_preventative_maintenances#hide", :as => :hide_bmet_preventative_maintenance 
  get "/bmet_preventative_maintenances/unhidden", to: "bmet_preventative_maintenances#index"
  get "/bmet_preventative_maintenances/unhidden/:id", to: "bmet_preventative_maintenances#show"
  get "/bmet_preventative_maintenances/hidden", to: "bmet_preventative_maintenances#hidden"
  get "/bmet_preventative_maintenances/hidden/:id", to: "bmet_preventative_maintenances#show_hidden"
  get "/bmet_preventative_maintenances/all", to: "bmet_preventative_maintenances#all"
  get "/bmet_preventative_maintenances/all/:id", to: "bmet_preventative_maintenances#show_all"
  put "/reset_bmet_preventative_maintenance/:id", to: "bmet_preventative_maintenances#reset"

  get "/facility_work_requests/:facility_id/public_new", to: "facility_work_requests#public_new"  
  post "/facility_work_requests/public_create", to: "facility_work_requests#public_create"  
  get "/facility_work_requests/public_show/:id", to: "facility_work_requests#public_show"  

  get "/bmet_work_requests/:facility_id/public_new", to: "bmet_work_requests#public_new"  
  post "/bmet_work_requests/public_create", to: "bmet_work_requests#public_create"  
  get "/bmet_work_requests/public_show/:id", to: "bmet_work_requests#public_show"  

  get "/my_bmet_work_orders", to: "bmet_work_orders#my"
  get "/detailed_bmet_work_orders", to: "bmet_work_orders#detailed"
  get "/detailed_items", to: "bmet_items#detailed"
  get "/text", to: "text#receive"

  get "/settings", to: "settings#index"
  post "/settings/create_user", to: "settings#create_user"
  post "/settings/create_department", to: "settings#create_department"
  post "/settings/create_item_group", to: "settings#create_item_group"
  post "/settings/update_user", to: "settings#update_user"

    
  get "/admin", to: "admin#index"
  get "/admin/print_tags_form", to: "admin#print_tags_form"

app/models/bmet_need.rb
# == Schema Information
#
# Table name: bmet_needs
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  department_id  :integer
#  bmet_model_id  :integer
#  quantity       :integer
#  urgency        :integer
#  reason         :text
#  remarks        :text
#  stage          :integer
#  date_requested :date
#  user_id        :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class BmetNeed < ActiveRecord::Base
    belongs_to :bmet_model
    belongs_to :department
    belongs_to :user
end

app/controllers/bmet_needs_controller.rb
class BmetNeedsController < ApplicationController
  load_and_authorize_resource
  before_action :set_need, only: [:show, :edit, :update, :destroy]

  # GET /needs
  # GET /needs.json
  def index
    @needs = BmetNeed.all
  end

  # GET /needs/1
  # GET /needs/1.json
  def show
  end

  # GET /needs/new
  def new
    @need = BmetNeed.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create
    @need = BmetNeed.new(need_params)

    respond_to do |format|
      if @need.save
        format.html { redirect_to @need, notice: 'BmetNeed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @need }
      else
        format.html { render action: 'new' }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    respond_to do |format|
      if @need.update(need_params)
        format.html { redirect_to @need, notice: 'BmetNeed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to bmet_needs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need
      @need = BmetNeed.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_params
      params.require(:bmet_need).permit(:name, :department_id, :bmet_model_id, :quantity, :urgency, :reason, :remarks, :stage, :date_requested, :user_id)
    end
end

app/helpers/bmet_needs_helper.rb
module BmetNeedsHelper
end

app/views/bmet_needs/_form.html.erb
<%= form_for(@need) do |f| %>
  <% if @need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>

      <ul>
      <% @need.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.number_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :bmet_model_id %><br>
    <%= f.number_field :bmet_model_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :urgency %><br>
    <%= f.number_field :urgency %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.number_field :stage %>
  </div>
  <div class="field">
    <%= f.label :date_requested %><br>
    <%= f.date_select :date_requested %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bmet_needs/edit.html.erb
<h1>Editing need</h1>

<%= render 'form' %>

<%= link_to 'Show', @need %> |
<%= link_to 'Back', bmet_needs_path %>

app/views/bmet_needs/index.html.erb
<h1><%= t(:listing).capitalize t(:need).capitalize.pluralize %></h1>

<table>
  <thead>
    <tr>
      <th><%= t(:name).capitalize%></th>
      <th><%= t(:location).capitalize%></th>
      <th><%= t(:model).capitalize%></th>
      <th><%= t(:quantity).capitalize%></th>
      <th><%= t(:urgency).capitalize%></th>
      <th><%= t(:reason).capitalize%></th>
      <th><%= t(:remarks).capitalize%></th>
      <th><%= t(:stage).capitalize%></th>
      <th><%= t(:date_requested).titlecase%></th>
      <th><%= t(:user).capitalize%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @needs.each do |need| %>
      <tr>
        <td><%= need.name %></td>
        <td><%= need.department_id %></td>
        <td><%= need.bmet_model_id %></td>
        <td><%= need.quantity %></td>
        <td><%= need.urgency %></td>
        <td><%= need.reason %></td>
        <td><%= need.remarks %></td>
        <td><%= need.stage %></td>
        <td><%= need.date_requested %></td>
        <td><%= need.user_id %></td>
        <td><%= link_to t(:show).capitalize, bmet_need %></td>
        <td><%= link_to t(:edit).capitalize, edit_bmet_need_path(need) %></td>
        <td><%= link_to t(:destroy).capitalize, need, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(:new).capitalize t(:need).capitalize, new_bmet_need_path %>

app/views/bmet_needs/new.html.erb
<h1>New need</h1>

<%= render 'form' %>

<%= link_to 'Back', bmet_needs_path %>

app/views/bmet_needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @need.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @need.department_id %>
</p>

<p>
  <strong>Model:</strong>
  <%= @need.bmet_model_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @need.quantity %>
</p>

<p>
  <strong>Urgency:</strong>
  <%= @need.urgency %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @need.reason %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @need.remarks %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @need.stage %>
</p>

<p>
  <strong>Date requested:</strong>
  <%= @need.date_requested %>
</p>

<p>
  <strong>User:</strong>
  <%= @need.user_id %>
</p>

<%= link_to 'Edit', edit_bmet_need_path(@need) %> |
<%= link_to 'Back', bmet_needs_path %>